export interface Technology {
  id: string;
  name: string;
  description: string;
  icon: string;
  category:
    | "language"
    | "framework"
    | "library"
    | "tool"
    | "database"
    | "platform";
  difficulty: "beginner" | "intermediate" | "advanced";
  popularity: number; // 1-5
  documentation: string;
  installation: string[];
  features: string[];
  useCases: string[];
}

export interface ProjectData {
  id: string;
  title: string;
  description: string;
  icon: string;
  color: string;
  technologies: Technology[];
  roadmap: {
    title: string;
    description: string;
    items: string[];
  }[];
  resources: {
    title: string;
    type: "documentation" | "tutorial" | "course" | "tool" | "template";
    url: string;
    description: string;
    free: boolean;
  }[];
}

export const projectsData: ProjectData[] = [
  {
    id: "web",
    title: "Aplicación Web",
    description: "Desarrollo de aplicaciones web modernas y responsive",
    icon: "web",
    color: "from-primary via-secondary to-accent",
    technologies: [
      {
        id: "react",
        name: "React",
        description:
          "Una biblioteca de JavaScript para construir interfaces de usuario interactivas y dinámicas.",
        icon: "react",
        category: "framework",
        difficulty: "intermediate",
        popularity: 5,
        documentation: "https://react.dev/",
        installation: ["npx create-react-app mi-app", "cd mi-app", "npm start"],
        features: [
          "Componentes reutilizables",
          "Virtual DOM para rendimiento optimizado",
          "Hooks para lógica de estado",
          "Gran ecosistema y comunidad",
          "React Router para navegación",
        ],
        useCases: [
          "SPAs (Single Page Applications)",
          "Dashboards interactivos",
          "E-commerce",
          "Redes sociales",
          "Aplicaciones de productividad",
        ],
      },
      {
        id: "nextjs",
        name: "Next.js",
        description:
          "Framework de React con renderizado del lado del servidor y generación de sitios estáticos.",
        icon: "nextjs",
        category: "framework",
        difficulty: "intermediate",
        popularity: 5,
        documentation: "https://nextjs.org/docs",
        installation: [
          "npx create-next-app@latest mi-app",
          "cd mi-app",
          "npm run dev",
        ],
        features: [
          "Renderizado del lado del servidor (SSR)",
          "Generación de sitios estáticos (SSG)",
          "API Routes integradas",
          "Optimización automática de imágenes",
          "File-based routing",
        ],
        useCases: [
          "Sitios web corporativos",
          "E-commerce de alto rendimiento",
          "Blogs y CMS",
          "Aplicaciones full-stack",
          "Landing pages optimizadas para SEO",
        ],
      },
      {
        id: "vue",
        name: "Vue.js",
        description:
          "Framework progresivo de JavaScript para construir interfaces de usuario.",
        icon: "vue",
        category: "framework",
        difficulty: "beginner",
        popularity: 4,
        documentation: "https://vuejs.org/",
        installation: [
          "npm create vue@latest mi-proyecto",
          "cd mi-proyecto",
          "npm install",
          "npm run dev",
        ],
        features: [
          "Curva de aprendizaje suave",
          "Composition API flexible",
          "Reactividad integrada",
          "Excelente documentación",
          "Ecosistema oficial (Router, Store)",
        ],
        useCases: [
          "Aplicaciones de mediana complejidad",
          "Prototipos rápidos",
          "Interfaces administrativas",
          "Aplicaciones progresivas (PWA)",
          "Integración en proyectos existentes",
        ],
      },
      {
        id: "angular",
        name: "Angular",
        description:
          "Plataforma y framework para construir aplicaciones web de una sola página usando TypeScript.",
        icon: "angular",
        category: "framework",
        difficulty: "advanced",
        popularity: 4,
        documentation: "https://angular.io/docs",
        installation: [
          "npm install -g @angular/cli",
          "ng new mi-app",
          "cd mi-app",
          "ng serve",
        ],
        features: [
          "Framework completo y opinionado",
          "TypeScript por defecto",
          "Dependency Injection",
          "CLI potente",
          "Arquitectura basada en componentes",
        ],
        useCases: [
          "Aplicaciones empresariales complejas",
          "Sistemas de gestión",
          "Aplicaciones bancarias",
          "Portales corporativos",
          "Aplicaciones de gran escala",
        ],
      },
    ],
    roadmap: [
      {
        title: "Fundamentos",
        description: "Conceptos básicos para comenzar",
        items: [
          "HTML5 semántico y accesibilidad",
          "CSS3 moderno (Flexbox, Grid, Variables)",
          "JavaScript ES6+ (Arrow functions, Destructuring, Modules)",
          "Responsive Design y Mobile First",
          "Git y control de versiones",
        ],
      },
      {
        title: "Framework Frontend",
        description: "Domina un framework principal",
        items: [
          "Elegir React, Vue o Angular",
          "Componentes y props/data binding",
          "Estado y gestión de eventos",
          "Routing y navegación",
          "Hooks/Composition API/Services",
        ],
      },
      {
        title: "Herramientas de Desarrollo",
        description: "Optimiza tu flujo de trabajo",
        items: [
          "Build tools (Vite, Webpack)",
          "Package managers (npm, yarn, pnpm)",
          "CSS frameworks (Tailwind, Bootstrap)",
          "Testing (Jest, Cypress, Testing Library)",
          "Linting y formatting (ESLint, Prettier)",
        ],
      },
      {
        title: "Temas Avanzados",
        description: "Mejora el rendimiento y la experiencia",
        items: [
          "Performance optimization",
          "Progressive Web Apps (PWA)",
          "Server-Side Rendering (SSR)",
          "Micro frontends",
          "Web Components",
        ],
      },
    ],
    resources: [
      {
        title: "MDN Web Docs",
        type: "documentation",
        url: "https://developer.mozilla.org/",
        description: "Documentación completa de tecnologías web",
        free: true,
      },
      {
        title: "Frontend Masters",
        type: "course",
        url: "https://frontendmasters.com/",
        description: "Cursos avanzados de desarrollo frontend",
        free: false,
      },
      {
        title: "Create React App",
        type: "template",
        url: "https://create-react-app.dev/",
        description: "Boilerplate oficial para proyectos React",
        free: true,
      },
      {
        title: "Vue.js Devtools",
        type: "tool",
        url: "https://devtools.vuejs.org/",
        description: "Extensión de navegador para debugging Vue",
        free: true,
      },
    ],
  },
  {
    id: "backend",
    title: "Backend/API REST",
    description: "Desarrollo de APIs y servicios backend robustos",
    icon: "api",
    color: "from-secondary via-accent to-primary",
    technologies: [
      {
        id: "nodejs",
        name: "Node.js",
        description:
          "Entorno de ejecución de JavaScript del lado del servidor basado en V8.",
        icon: "nodejs",
        category: "platform",
        difficulty: "intermediate",
        popularity: 5,
        documentation: "https://nodejs.org/docs/",
        installation: [
          "Descargar desde nodejs.org",
          "npm init -y",
          "npm install express",
          "Crear servidor básico",
        ],
        features: [
          "Event-driven y non-blocking I/O",
          "NPM con millones de paquetes",
          "JavaScript en el backend",
          "Excelente para APIs REST",
          "Microservicios y aplicaciones real-time",
        ],
        useCases: [
          "APIs REST y GraphQL",
          "Microservicios",
          "Aplicaciones real-time (chat, gaming)",
          "Herramientas de desarrollo",
          "Servicios de streaming",
        ],
      },
      {
        id: "express",
        name: "Express.js",
        description: "Framework web minimalista y flexible para Node.js.",
        icon: "express",
        category: "framework",
        difficulty: "beginner",
        popularity: 5,
        documentation: "https://expressjs.com/",
        installation: [
          "npm install express",
          "const express = require('express')",
          "const app = express()",
          "app.listen(3000)",
        ],
        features: [
          "Minimalista y no opinionado",
          "Middleware system potente",
          "Routing robusto",
          "Gran ecosistema",
          "Perfecto para APIs REST",
        ],
        useCases: [
          "APIs REST simples y complejas",
          "Aplicaciones web tradicionales",
          "Proxy servers",
          "Middleware personalizado",
          "Prototipado rápido",
        ],
      },
      {
        id: "python",
        name: "Python",
        description:
          "Lenguaje de programación de alto nivel, interpretado y de propósito general.",
        icon: "python",
        category: "language",
        difficulty: "beginner",
        popularity: 5,
        documentation: "https://docs.python.org/",
        installation: [
          "Descargar desde python.org",
          "pip install flask/django",
          "python -m venv venv",
          "source venv/bin/activate",
        ],
        features: [
          "Sintaxis clara y legible",
          "Ecosistema rico en bibliotecas",
          "Excelente para data science",
          "Frameworks web maduros",
          "Comunidad activa y grande",
        ],
        useCases: [
          "APIs y servicios web",
          "Data science y ML",
          "Automatización y scripting",
          "Aplicaciones científicas",
          "Desarrollo rápido de prototipos",
        ],
      },
    ],
    roadmap: [
      {
        title: "Fundamentos de Backend",
        description: "Conceptos esenciales del desarrollo backend",
        items: [
          "HTTP y protocolos de comunicación",
          "APIs REST y diseño de endpoints",
          "Bases de datos relacionales y NoSQL",
          "Autenticación y autorización",
          "Seguridad web básica",
        ],
      },
      {
        title: "Lenguaje y Framework",
        description: "Domina tu stack principal",
        items: [
          "Node.js/Python/Java/C# - elige uno",
          "Framework web (Express, Django, Spring)",
          "ORM/ODM para bases de datos",
          "Validation y error handling",
          "Testing unitario e integración",
        ],
      },
      {
        title: "Bases de Datos",
        description: "Gestión de datos eficiente",
        items: [
          "SQL y diseño de esquemas",
          "PostgreSQL/MySQL",
          "MongoDB/Redis (NoSQL)",
          "Migrations y seeds",
          "Query optimization",
        ],
      },
      {
        title: "DevOps y Despliegue",
        description: "Lleva tu aplicación a producción",
        items: [
          "Docker y containerización",
          "CI/CD pipelines",
          "Cloud deployment (AWS, GCP, Azure)",
          "Monitoring y logging",
          "Load balancing y escalabilidad",
        ],
      },
    ],
    resources: [
      {
        title: "Node.js Best Practices",
        type: "documentation",
        url: "https://github.com/goldbergyoni/nodebestpractices",
        description: "Guía completa de mejores prácticas para Node.js",
        free: true,
      },
      {
        title: "Postman",
        type: "tool",
        url: "https://www.postman.com/",
        description: "Herramienta para testing de APIs",
        free: true,
      },
      {
        title: "Express.js Template",
        type: "template",
        url: "https://github.com/expressjs/generator",
        description: "Generador de aplicaciones Express",
        free: true,
      },
    ],
  },

  {
    id: "multiplataforma",
    title: "Multiplataforma",
    description: "Aplicaciones que funcionan en múltiples plataformas",
    icon: "mobile",
    color: "from-accent via-primary to-secondary",
    technologies: [
      {
        id: "react-native",
        name: "React Native",
        description:
          "Framework para desarrollar aplicaciones móviles nativas usando React y JavaScript.",
        icon: "react-native",
        category: "framework",
        difficulty: "intermediate",
        popularity: 5,
        documentation: "https://reactnative.dev/",
        installation: [
          "npx @react-native-community/cli@latest init AwesomeProject",
          "cd AwesomeProject",
          "npx react-native run-android # o run-ios",
          "# Instalar Android Studio y/o Xcode",
        ],
        features: [
          "Código compartido entre iOS y Android",
          "Componentes nativos reales",
          "Hot Reload para desarrollo rápido",
          "Acceso completo a APIs nativas",
          "Gran ecosistema de librerías",
        ],
        useCases: [
          "Apps móviles multiplataforma",
          "MVPs y prototipos rápidos",
          "Apps con lógica de negocio compleja",
          "E-commerce móvil",
          "Redes sociales y chat apps",
        ],
      },
      {
        id: "flutter",
        name: "Flutter",
        description:
          "Framework de Google para crear aplicaciones multiplataforma con un solo código base usando Dart.",
        icon: "flutter",
        category: "framework",
        difficulty: "intermediate",
        popularity: 5,
        documentation: "https://flutter.dev/docs",
        installation: [
          "Descargar Flutter SDK desde flutter.dev",
          "Agregar Flutter al PATH",
          "flutter doctor # verificar instalación",
          "flutter create mi_app && cd mi_app && flutter run",
        ],
        features: [
          "UI consistente en todas las plataformas",
          "Rendimiento nativo compilado",
          "Hot Reload ultrarrápido",
          "Widget system altamente customizable",
          "Soporte para Web, Desktop y Embedded",
        ],
        useCases: [
          "Apps móviles de alto rendimiento",
          "Aplicaciones con UI compleja",
          "Apps multiplataforma (móvil, web, desktop)",
          "Juegos 2D casuales",
          "Apps empresariales",
        ],
      },
      {
        id: "ionic",
        name: "Ionic",
        description:
          "Framework para construir aplicaciones híbridas usando tecnologías web (HTML, CSS, JS).",
        icon: "ionic",
        category: "framework",
        difficulty: "beginner",
        popularity: 4,
        documentation: "https://ionicframework.com/docs",
        installation: [
          "npm install -g @ionic/cli",
          "ionic start myApp tabs --type=angular",
          "cd myApp",
          "ionic serve",
        ],
        features: [
          "Basado en tecnologías web estándar",
          "UI Components pre-diseñados",
          "Capacitor para acceso nativo",
          "Soporte para Angular, React y Vue",
          "Deploy fácil en app stores",
        ],
        useCases: [
          "Apps híbridas rápidas",
          "Prototipado de apps móviles",
          "Apps con mucho contenido web",
          "PWAs (Progressive Web Apps)",
          "Apps empresariales internas",
        ],
      },
      {
        id: "xamarin",
        name: "Xamarin",
        description:
          "Plataforma de Microsoft para desarrollar aplicaciones nativas multiplataforma con C#.",
        icon: "xamarin",
        category: "framework",
        difficulty: "advanced",
        popularity: 3,
        documentation: "https://docs.microsoft.com/xamarin/",
        installation: [
          "Instalar Visual Studio con Xamarin workload",
          "Configurar Android SDK y/o Xcode",
          "Crear nuevo proyecto Xamarin.Forms",
          "Seleccionar plantilla y plataformas target",
        ],
        features: [
          "100% acceso a APIs nativas",
          "Compartir hasta 90% del código",
          "Integración completa con .NET",
          "Debugging y testing avanzado",
          "Soporte empresarial de Microsoft",
        ],
        useCases: [
          "Apps empresariales complejas",
          "Aplicaciones con lógica de negocio en .NET",
          "Integración con servicios Microsoft",
          "Apps que requieren máximo rendimiento",
          "Proyectos con equipos .NET existentes",
        ],
      },
      {
        id: "capacitor",
        name: "Capacitor",
        description:
          "Runtime nativo que permite ejecutar aplicaciones web como apps nativas en móviles y desktop.",
        icon: "capacitor",
        category: "platform",
        difficulty: "beginner",
        popularity: 4,
        documentation: "https://capacitorjs.com/docs",
        installation: [
          "npm install @capacitor/core @capacitor/cli",
          "npx cap init",
          "npm install @capacitor/android @capacitor/ios",
          "npx cap add android && npx cap add ios",
        ],
        features: [
          "Ejecuta apps web como nativas",
          "Plugin system extensible",
          "Acceso completo a APIs nativas",
          "Compatible con cualquier framework web",
          "Deploy directo desde web build",
        ],
        useCases: [
          "Convertir PWAs en apps nativas",
          "Apps híbridas modernas",
          "Migración de Cordova/PhoneGap",
          "Apps con mucha lógica web existente",
          "Prototipado rápido móvil",
        ],
      },
      {
        id: "electron",
        name: "Electron",
        description:
          "Framework para crear aplicaciones de escritorio multiplataforma usando tecnologías web.",
        icon: "electron",
        category: "framework",
        difficulty: "intermediate",
        popularity: 4,
        documentation: "https://www.electronjs.org/docs",
        installation: [
          "npm install electron --save-dev",
          "Crear main.js y index.html",
          "Agregar script start en package.json",
          "npm start",
        ],
        features: [
          "Apps desktop con tecnologías web",
          "Acceso completo al sistema operativo",
          "Auto-updater integrado",
          "Distribución fácil multiplataforma",
          "Debugging con DevTools",
        ],
        useCases: [
          "Aplicaciones de escritorio modernas",
          "Editores de código y IDEs",
          "Herramientas de productividad",
          "Apps de comunicación (Slack, Discord)",
          "Herramientas de desarrollo",
        ],
      },
    ],
    roadmap: [
      {
        title: "Fundamentos Multiplataforma",
        description: "Conceptos esenciales para desarrollo multiplataforma",
        items: [
          "Entender diferencias entre nativo, híbrido y multiplataforma",
          "Arquitectura de aplicaciones móviles",
          "Diseño responsive y adaptive",
          "Gestión de estado en aplicaciones móviles",
          "Navegación y UX en móviles",
        ],
      },
      {
        title: "Elegir tu Stack Principal",
        description: "Selecciona y domina una tecnología",
        items: [
          "React Native (si vienes de React)",
          "Flutter (para máximo rendimiento)",
          "Ionic (si prefieres tecnologías web)",
          "Xamarin (para ecosistemas .NET)",
          "Configuración del entorno de desarrollo",
        ],
      },
      {
        title: "Desarrollo y Testing",
        description: "Construcción y pruebas de aplicaciones",
        items: [
          "Componentes y layouts responsive",
          "Manejo de formularios y validaciones",
          "Integración con APIs REST/GraphQL",
          "Testing en dispositivos reales y emuladores",
          "Debug y profiling de rendimiento",
        ],
      },
      {
        title: "Funcionalidades Avanzadas",
        description: "Características nativas y optimización",
        items: [
          "Acceso a cámara, GPS y sensores",
          "Notificaciones push",
          "Almacenamiento local y offline-first",
          "Optimización de rendimiento y batería",
          "Internacionalización (i18n)",
        ],
      },
      {
        title: "Distribución y Mantenimiento",
        description: "Deploy y ciclo de vida de la app",
        items: [
          "Build y empaquetado para producción",
          "Publicación en App Store y Google Play",
          "CI/CD para apps móviles",
          "Analytics y crash reporting",
          "Actualizaciones OTA (Over The Air)",
        ],
      },
    ],
    resources: [
      {
        title: "React Native Official Docs",
        type: "documentation",
        url: "https://reactnative.dev/",
        description: "Documentación oficial completa de React Native",
        free: true,
      },
      {
        title: "Flutter University",
        type: "course",
        url: "https://flutter.dev/learn",
        description: "Cursos oficiales y codelabs de Flutter",
        free: true,
      },
      {
        title: "Expo",
        type: "documentation",
        url: "https://expo.dev/",
        description: "Plataforma para desarrollar y deployar apps React Native",
        free: true,
      },
      {
        title: "Ionic UI Components",
        type: "tool",
        url: "https://ionicframework.com/docs/components",
        description: "Biblioteca completa de componentes UI de Ionic",
        free: true,
      },
      {
        title: "React Native Elements",
        type: "template",
        url: "https://reactnativeelements.com/",
        description: "Kit de componentes UI para React Native",
        free: true,
      },
      {
        title: "Flutter Awesome",
        type: "tool",
        url: "https://github.com/Solido/awesome-flutter",
        description: "Lista curada de recursos increíbles para Flutter",
        free: true,
      },
      {
        title: "The Complete React Native Course",
        type: "course",
        url: "https://www.udemy.com/course/the-complete-react-native-and-redux-course/",
        description: "Curso completo de React Native en Udemy",
        free: false,
      },
      {
        title: "Flipper",
        type: "tool",
        url: "https://fbflipper.com/",
        description: "Herramienta de debugging para apps móviles",
        free: true,
      },
    ],
  },
  // Agregar este objeto al array projectsData en src/constants/projectData.ts

  {
    id: "android",
    title: "Android",
    description: "Aplicaciones nativas para el ecosistema Android",
    icon: "android",
    color: "from-green-500 via-green-600 to-green-700",
    technologies: [
      {
        id: "kotlin",
        name: "Kotlin",
        description:
          "Lenguaje de programación moderno, conciso y seguro, oficial para desarrollo Android.",
        icon: "kotlin",
        category: "language",
        difficulty: "intermediate",
        popularity: 5,
        documentation: "https://kotlinlang.org/docs/",
        installation: [
          "Instalar Android Studio (incluye Kotlin)",
          "Crear nuevo proyecto Android con Kotlin",
          "Configurar Kotlin en build.gradle",
          "// Kotlin viene preconfigurado en proyectos nuevos",
        ],
        features: [
          "100% interoperable con Java",
          "Null safety integrada",
          "Sintaxis concisa y expresiva",
          "Corrutinas para programación asíncrona",
          "Soporte oficial de Google para Android",
        ],
        useCases: [
          "Desarrollo nativo Android",
          "Aplicaciones multiplataforma con KMM",
          "Backend con Ktor",
          "Scripting y automatización",
          "Migración gradual desde Java",
        ],
      },
      {
        id: "jetpack-compose",
        name: "Jetpack Compose",
        description:
          "Kit de herramientas moderno para construir UI nativas de Android de forma declarativa.",
        icon: "compose",
        category: "framework",
        difficulty: "intermediate",
        popularity: 5,
        documentation: "https://developer.android.com/jetpack/compose",
        installation: [
          "Android Studio Arctic Fox o superior",
          "compileSdk 34 o superior",
          "implementation 'androidx.compose.ui:ui:$compose_version'",
          "Habilitar compose en build.gradle",
        ],
        features: [
          "UI declarativa como React",
          "Menos código boilerplate",
          "Preview en tiempo real",
          "Interoperabilidad con Views",
          "Animaciones fluidas integradas",
        ],
        useCases: [
          "UIs modernas y dinámicas",
          "Aplicaciones con animaciones complejas",
          "Nuevos proyectos Android",
          "Migración gradual desde Views",
          "Prototipado rápido de interfaces",
        ],
      },
      {
        id: "android-studio",
        name: "Android Studio",
        description:
          "IDE oficial para desarrollo Android basado en IntelliJ IDEA con herramientas especializadas.",
        icon: "android-studio",
        category: "tool",
        difficulty: "beginner",
        popularity: 5,
        documentation: "https://developer.android.com/studio",
        installation: [
          "Descargar desde developer.android.com/studio",
          "Instalar Android SDK y herramientas",
          "Configurar emulador o dispositivo físico",
          "Crear primer proyecto Android",
        ],
        features: [
          "Editor inteligente con autocompletado",
          "Emulador rápido integrado",
          "Debugging avanzado y profiling",
          "Layout editor visual",
          "Integración con Git y testing",
        ],
        useCases: [
          "Desarrollo nativo Android",
          "Debugging y profiling de apps",
          "Diseño de layouts visuales",
          "Testing en múltiples dispositivos",
          "Análisis de rendimiento",
        ],
      },
      {
        id: "room",
        name: "Room",
        description:
          "Biblioteca de persistencia que proporciona una capa de abstracción sobre SQLite.",
        icon: "room",
        category: "library",
        difficulty: "intermediate",
        popularity: 5,
        documentation:
          "https://developer.android.com/training/data-storage/room",
        installation: [
          "implementation 'androidx.room:room-runtime:$room_version'",
          "kapt 'androidx.room:room-compiler:$room_version'",
          "implementation 'androidx.room:room-ktx:$room_version'",
          "Configurar entidades, DAO y Database",
        ],
        features: [
          "Type safety en tiempo de compilación",
          "Queries SQL verificadas",
          "Migración automática de esquemas",
          "Integración con LiveData y Flow",
          "Testing de base de datos simplificado",
        ],
        useCases: [
          "Almacenamiento local estructurado",
          "Cache de datos offline",
          "Apps con datos complejos",
          "Sincronización local-remota",
          "Apps que requieren consultas SQL",
        ],
      },
      {
        id: "retrofit",
        name: "Retrofit",
        description:
          "Cliente HTTP type-safe para Android y Java, ideal para consumir APIs REST.",
        icon: "retrofit",
        category: "library",
        difficulty: "beginner",
        popularity: 5,
        documentation: "https://square.github.io/retrofit/",
        installation: [
          "implementation 'com.squareup.retrofit2:retrofit:$retrofit_version'",
          "implementation 'com.squareup.retrofit2:converter-gson:$retrofit_version'",
          "Definir interfaces de API",
          "Configurar Retrofit instance",
        ],
        features: [
          "Conversión automática JSON",
          "Interceptors para logging y auth",
          "Soporte para RxJava y Corrutinas",
          "Request/Response customizable",
          "Manejo de errores integrado",
        ],
        useCases: [
          "Consumo de APIs REST",
          "Autenticación con tokens",
          "Upload/download de archivos",
          "Logging de requests HTTP",
          "Manejo de errores de red",
        ],
      },
      {
        id: "material-design",
        name: "Material Design",
        description:
          "Sistema de diseño de Google que proporciona componentes y guidelines para Android.",
        icon: "material",
        category: "library",
        difficulty: "beginner",
        popularity: 5,
        documentation: "https://material.io/develop/android",
        installation: [
          "implementation 'com.google.android.material:material:$material_version'",
          "Aplicar tema Material en styles.xml",
          "Usar componentes Material en layouts",
          "Configurar colores y tipografía",
        ],
        features: [
          "Componentes UI consistentes",
          "Animaciones y transiciones fluidas",
          "Temas claro/oscuro automáticos",
          "Accesibilidad integrada",
          "Actualización constante con nuevos components",
        ],
        useCases: [
          "Apps con UI moderna y consistente",
          "Implementación de Material You",
          "Aplicaciones empresariales",
          "Apps que siguen Android guidelines",
          "Prototipado con componentes estándar",
        ],
      },
    ],
    roadmap: [
      {
        title: "Fundamentos de Android",
        description: "Conceptos esenciales para comenzar",
        items: [
          "Arquitectura de Android (Activities, Fragments, Services)",
          "Ciclo de vida de componentes",
          "Layouts y Views básicos",
          "Recursos (strings, colores, dimensiones)",
          "Gradle y estructura de proyectos Android",
        ],
      },
      {
        title: "Kotlin y UI Moderno",
        description: "Domina el lenguaje y interfaces modernas",
        items: [
          "Kotlin fundamentals y características avanzadas",
          "Jetpack Compose para UI declarativa",
          "Material Design 3 y theming",
          "Navigation Component",
          "Manejo de estado en Compose",
        ],
      },
      {
        title: "Arquitectura y Datos",
        description: "Patrones de arquitectura y gestión de datos",
        items: [
          "MVVM y arquitectura limpia",
          "Room para base de datos local",
          "Retrofit para networking",
          "Repository pattern",
          "Dependency Injection con Hilt",
        ],
      },
      {
        title: "Funcionalidades Avanzadas",
        description: "Características nativas de Android",
        items: [
          "Permisos y seguridad",
          "Cámara y multimedia",
          "Sensores y location services",
          "Notificaciones push (FCM)",
          "Background tasks y WorkManager",
        ],
      },
      {
        title: "Testing y Distribución",
        description: "Calidad y publicación",
        items: [
          "Unit testing con JUnit y Mockito",
          "UI testing con Espresso",
          "Debugging y profiling",
          "Play Console y app signing",
          "CI/CD con GitHub Actions",
        ],
      },
    ],
    resources: [
      {
        title: "Android Developers",
        type: "documentation",
        url: "https://developer.android.com/",
        description: "Documentación oficial completa de Android",
        free: true,
      },
      {
        title: "Android Basics with Compose",
        type: "course",
        url: "https://developer.android.com/courses/android-basics-compose/course",
        description: "Curso oficial gratuito de Google para principiantes",
        free: true,
      },
      {
        title: "Kotlin Koans",
        type: "tutorial",
        url: "https://kotlinlang.org/docs/koans.html",
        description: "Ejercicios interactivos para aprender Kotlin",
        free: true,
      },
      {
        title: "Material Design Components",
        type: "tool",
        url: "https://material.io/components",
        description: "Biblioteca completa de componentes Material",
        free: true,
      },
      {
        title: "Android Architecture Samples",
        type: "template",
        url: "https://github.com/android/architecture-samples",
        description: "Ejemplos oficiales de arquitectura Android",
        free: true,
      },
      {
        title: "The Complete Android Developer Course",
        type: "course",
        url: "https://www.udemy.com/course/complete-android-n-developer-course/",
        description: "Curso completo de Android development",
        free: false,
      },
      {
        title: "Scrcpy",
        type: "tool",
        url: "https://github.com/Genymobile/scrcpy",
        description: "Herramienta para controlar dispositivos Android desde PC",
        free: true,
      },
      {
        title: "LeakCanary",
        type: "tool",
        url: "https://square.github.io/leakcanary/",
        description: "Biblioteca para detectar memory leaks en Android",
        free: true,
      },
    ],
  },
  // Agregar este objeto al array projectsData en src/constants/projectData.ts

  {
    id: "ios",
    title: "iOS",
    description: "Aplicaciones nativas para iPhone y iPad",
    icon: "ios",
    color: "from-blue-500 via-blue-600 to-blue-700",
    technologies: [
      {
        id: "swift",
        name: "Swift",
        description:
          "Lenguaje de programación potente e intuitivo desarrollado por Apple para iOS, macOS, watchOS y tvOS.",
        icon: "swift",
        category: "language",
        difficulty: "intermediate",
        popularity: 5,
        documentation: "https://docs.swift.org/swift-book/",
        installation: [
          "Instalar Xcode desde Mac App Store",
          "Swift viene incluido con Xcode",
          "Crear nuevo proyecto iOS en Xcode",
          "Seleccionar Swift como lenguaje",
        ],
        features: [
          "Sintaxis clara y expresiva",
          "Type safety y memory safety",
          "Rendimiento optimizado",
          "Interoperabilidad con Objective-C",
          "Playgrounds para experimentación",
        ],
        useCases: [
          "Desarrollo nativo iOS/macOS",
          "Aplicaciones de alto rendimiento",
          "Apps que usan características avanzadas del sistema",
          "Prototipos con Swift Playgrounds",
          "Desarrollo multiplataforma Apple",
        ],
      },
      {
        id: "swiftui",
        name: "SwiftUI",
        description:
          "Framework declarativo de Apple para construir interfaces de usuario en todos los dispositivos Apple.",
        icon: "swiftui",
        category: "framework",
        difficulty: "intermediate",
        popularity: 5,
        documentation: "https://developer.apple.com/xcode/swiftui/",
        installation: [
          "Xcode 11+ requerido",
          "iOS 13+ target deployment",
          "import SwiftUI en archivos Swift",
          "Usar @main App con WindowGroup",
        ],
        features: [
          "UI declarativa como React",
          "Live Preview en Xcode",
          "Data binding automático",
          "Animaciones fluidas integradas",
          "Multiplataforma (iOS, macOS, watchOS, tvOS)",
        ],
        useCases: [
          "Apps modernas con UI dinámica",
          "Aplicaciones multiplataforma Apple",
          "Prototipado rápido de interfaces",
          "Apps con animaciones complejas",
          "Nuevos proyectos iOS 13+",
        ],
      },
      {
        id: "uikit",
        name: "UIKit",
        description:
          "Framework fundamental para construir interfaces de usuario en iOS y tvOS de forma imperativa.",
        icon: "uikit",
        category: "framework",
        difficulty: "intermediate",
        popularity: 4,
        documentation: "https://developer.apple.com/documentation/uikit",
        installation: [
          "Incluido en iOS SDK",
          "import UIKit en archivos Swift",
          "Crear ViewControllers y Views",
          "Configurar Storyboards o código",
        ],
        features: [
          "Control total sobre la UI",
          "Soporte completo para iOS legacy",
          "Integración con Core Animation",
          "Gesture recognizers avanzados",
          "Customización profunda de componentes",
        ],
        useCases: [
          "Apps que requieren control granular de UI",
          "Mantenimiento de apps existentes",
          "Componentes custom complejos",
          "Apps con soporte iOS < 13",
          "Integración con bibliotecas third-party",
        ],
      },
      {
        id: "xcode",
        name: "Xcode",
        description:
          "IDE oficial de Apple para desarrollo en todas las plataformas Apple con herramientas integradas.",
        icon: "xcode",
        category: "tool",
        difficulty: "beginner",
        popularity: 5,
        documentation: "https://developer.apple.com/xcode/",
        installation: [
          "Descargar desde Mac App Store",
          "Instalar Command Line Tools",
          "Configurar Apple Developer Account",
          "Instalar simuladores iOS",
        ],
        features: [
          "Interface Builder visual",
          "Debugging integrado con LLDB",
          "Simuladores de todos los dispositivos",
          "Instruments para profiling",
          "Git integration y Source Control",
        ],
        useCases: [
          "Desarrollo completo de apps iOS",
          "Debugging y profiling avanzado",
          "Design de interfaces visuales",
          "Testing en simuladores",
          "Distribución a App Store",
        ],
      },
      {
        id: "coredata",
        name: "Core Data",
        description:
          "Framework de Apple para gestión de objetos y persistencia de datos con un modelo objeto-relacional.",
        icon: "coredata",
        category: "framework",
        difficulty: "advanced",
        popularity: 4,
        documentation: "https://developer.apple.com/documentation/coredata",
        installation: [
          "Incluido en iOS SDK",
          "import CoreData",
          "Crear Data Model (.xcdatamodeld)",
          "Configurar NSPersistentContainer",
        ],
        features: [
          "Object-relational mapping automático",
          "Lazy loading y faulting",
          "Migration automática de esquemas",
          "Optimización de memoria y rendimiento",
          "Integración con CloudKit",
        ],
        useCases: [
          "Apps con datos complejos y relacionales",
          "Almacenamiento offline robusto",
          "Apps que requieren migraciones de esquema",
          "Sincronización con iCloud",
          "Aplicaciones empresariales con mucha data",
        ],
      },
      {
        id: "alamofire",
        name: "Alamofire",
        description:
          "Biblioteca HTTP elegante escrita en Swift para iOS, macOS, watchOS y tvOS.",
        icon: "alamofire",
        category: "library",
        difficulty: "beginner",
        popularity: 5,
        documentation: "https://alamofire.github.io/Alamofire/",
        installation: [
          "CocoaPods: pod 'Alamofire'",
          "Swift Package Manager en Xcode",
          "Carthage: github 'Alamofire/Alamofire'",
          "import Alamofire en archivos Swift",
        ],
        features: [
          "API elegante y Swift-native",
          "Request/Response interceptors",
          "JSON encoding/decoding automático",
          "Network reachability monitoring",
          "Comprehensive testing suite",
        ],
        useCases: [
          "Consumo de APIs REST",
          "Upload/download de archivos",
          "Autenticación con tokens",
          "Monitoring de conectividad",
          "Testing de requests HTTP",
        ],
      },
    ],
    roadmap: [
      {
        title: "Fundamentos de iOS",
        description: "Conceptos esenciales del desarrollo iOS",
        items: [
          "Arquitectura de iOS (MVC, MVVM)",
          "View Controllers y Navigation",
          "Auto Layout y responsive design",
          "iOS Human Interface Guidelines",
          "Xcode básico y simuladores",
        ],
      },
      {
        title: "Swift y UI Framework",
        description: "Domina el lenguaje y la construcción de interfaces",
        items: [
          "Swift fundamentals y características avanzadas",
          "SwiftUI para UI declarativa moderna",
          "UIKit para control granular (opcional)",
          "Programmatic UI vs Storyboards",
          "Navigation y data passing",
        ],
      },
      {
        title: "Datos y Networking",
        description: "Gestión de datos y comunicación",
        items: [
          "Core Data para persistencia local",
          "UserDefaults para configuraciones",
          "Alamofire para networking",
          "JSON parsing con Codable",
          "Offline-first architecture",
        ],
      },
      {
        title: "Funcionalidades iOS",
        description: "Características específicas de iOS",
        items: [
          "Core Location y MapKit",
          "Camera y Photo Library",
          "Push Notifications (APNs)",
          "Biometric authentication (Touch/Face ID)",
          "HealthKit, ARKit, Core ML",
        ],
      },
      {
        title: "Testing y App Store",
        description: "Calidad y distribución",
        items: [
          "Unit testing con XCTest",
          "UI testing y snapshot testing",
          "TestFlight para beta testing",
          "App Store Connect y review process",
          "Analytics y crash reporting",
        ],
      },
    ],
    resources: [
      {
        title: "Apple Developer Documentation",
        type: "documentation",
        url: "https://developer.apple.com/documentation/",
        description: "Documentación oficial completa de Apple",
        free: true,
      },
      {
        title: "SwiftUI Tutorials",
        type: "tutorial",
        url: "https://developer.apple.com/tutorials/swiftui",
        description: "Tutoriales oficiales de SwiftUI de Apple",
        free: true,
      },
      {
        title: "Hacking with Swift",
        type: "course",
        url: "https://www.hackingwithswift.com/",
        description: "Tutoriales y cursos completos de Swift e iOS",
        free: true,
      },
      {
        title: "iOS App Dev with SwiftUI",
        type: "course",
        url: "https://cs193p.stanford.edu/",
        description: "Curso de Stanford sobre desarrollo iOS",
        free: true,
      },
      {
        title: "Ray Wenderlich iOS Tutorials",
        type: "tutorial",
        url: "https://www.kodeco.com/ios",
        description: "Tutoriales avanzados y deep dives de iOS",
        free: false,
      },
      {
        title: "SF Symbols",
        type: "tool",
        url: "https://developer.apple.com/sf-symbols/",
        description: "Biblioteca oficial de iconos de Apple",
        free: true,
      },
      {
        title: "iOS App Templates",
        type: "template",
        url: "https://github.com/app-developers/ios-app-templates",
        description: "Templates y boilerplates para apps iOS",
        free: true,
      },
      {
        title: "Instruments",
        type: "tool",
        url: "https://developer.apple.com/xcode/features/",
        description: "Herramientas de profiling integradas en Xcode",
        free: true,
      },
    ],
  },
  // Agregar este objeto al array projectsData en src/constants/projectData.ts

  {
    id: "videojuegos",
    title: "Videojuegos",
    description: "Desarrollo de videojuegos para diferentes plataformas",
    icon: "game",
    color: "from-purple-500 via-pink-500 to-red-500",
    technologies: [
      {
        id: "unity",
        name: "Unity",
        description:
          "Motor de juegos multiplataforma líder en la industria, ideal para juegos 2D, 3D, VR y AR.",
        icon: "unity",
        category: "platform",
        difficulty: "intermediate",
        popularity: 5,
        documentation: "https://docs.unity3d.com/",
        installation: [
          "Descargar Unity Hub desde unity.com",
          "Instalar versión LTS recomendada",
          "Agregar módulos de plataforma (Android, iOS, etc.)",
          "Crear nuevo proyecto desde Unity Hub",
        ],
        features: [
          "Desarrollo multiplataforma sin código adicional",
          "Editor visual potente e intuitivo",
          "Asset Store con miles de recursos",
          "Scripting en C# con .NET",
          "Soporte completo para VR/AR y 3D avanzado",
        ],
        useCases: [
          "Juegos móviles 2D y 3D",
          "Juegos indie y AAA",
          "Aplicaciones VR/AR",
          "Simulaciones y visualizaciones",
          "Juegos multiplataforma (PC, consolas, móvil)",
        ],
      },
      {
        id: "unreal-engine",
        name: "Unreal Engine",
        description:
          "Motor de juegos de Epic Games conocido por gráficos de alta calidad y juegos AAA.",
        icon: "unreal",
        category: "platform",
        difficulty: "advanced",
        popularity: 5,
        documentation: "https://docs.unrealengine.com/",
        installation: [
          "Crear cuenta en Epic Games",
          "Descargar Epic Games Launcher",
          "Instalar Unreal Engine desde el launcher",
          "Crear nuevo proyecto con template",
        ],
        features: [
          "Gráficos fotorrealistas de última generación",
          "Blueprints para programación visual",
          "Lumen para iluminación global dinámica",
          "Nanite para geometría virtualizada",
          "Marketplace con assets premium",
        ],
        useCases: [
          "Juegos AAA con gráficos avanzados",
          "Juegos de PC y consolas",
          "Experiencias VR inmersivas",
          "Architectural visualization",
          "Películas y cinematics en tiempo real",
        ],
      },
      {
        id: "godot",
        name: "Godot",
        description:
          "Motor de juegos open source, ligero y versátil, perfecto para desarrolladores indie.",
        icon: "godot",
        category: "platform",
        difficulty: "beginner",
        popularity: 4,
        documentation: "https://docs.godotengine.org/",
        installation: [
          "Descargar desde godotengine.org",
          "Ejecutar archivo (.exe en Windows, .dmg en Mac)",
          "No requiere instalación, es portable",
          "Crear nuevo proyecto desde Project Manager",
        ],
        features: [
          "100% gratuito y open source",
          "Tamaño pequeño (~40MB)",
          "GDScript fácil de aprender",
          "Editor integrado para todo",
          "Scene system único y flexible",
        ],
        useCases: [
          "Juegos indie 2D y 3D",
          "Prototipado rápido de juegos",
          "Juegos educativos",
          "Primeros proyectos de game dev",
          "Juegos experimentales y arte interactivo",
        ],
      },
      {
        id: "phaser",
        name: "Phaser",
        description:
          "Framework JavaScript para crear juegos HTML5 que se ejecutan en navegadores web.",
        icon: "phaser",
        category: "framework",
        difficulty: "intermediate",
        popularity: 4,
        documentation: "https://phaser.io/learn",
        installation: [
          "npm install phaser",
          "Crear archivo HTML con canvas",
          "import Phaser from 'phaser'",
          "Configurar game config y scenes",
        ],
        features: [
          "Juegos que corren en cualquier navegador",
          "WebGL y Canvas rendering",
          "Physics engines integrados",
          "Audio y input management",
          "Deployment simple en web",
        ],
        useCases: [
          "Juegos casuales para web",
          "Juegos educativos online",
          "Prototipos de juegos rápidos",
          "Juegos de redes sociales",
          "Portfolio interactivo y mini-games",
        ],
      },
      {
        id: "gamemaker",
        name: "GameMaker Studio",
        description:
          "Herramienta especializada en juegos 2D con potente editor visual y GML scripting.",
        icon: "gamemaker",
        category: "platform",
        difficulty: "beginner",
        popularity: 4,
        documentation: "https://manual.yoyogames.com/",
        installation: [
          "Crear cuenta en YoYo Games",
          "Descargar GameMaker Studio",
          "Activar licencia (free trial disponible)",
          "Crear nuevo proyecto 2D",
        ],
        features: [
          "Especializado en juegos 2D pixel-perfect",
          "Visual scripting drag-and-drop",
          "GML para scripting avanzado",
          "Workflow optimizado para 2D",
          "Export a múltiples plataformas",
        ],
        useCases: [
          "Juegos 2D indie y retro",
          "Pixel art games",
          "Juegos de plataformas y arcade",
          "Prototipado rápido 2D",
          "Juegos móviles casuales",
        ],
      },
      {
        id: "construct3",
        name: "Construct 3",
        description:
          "Motor de juegos basado en navegador con desarrollo completamente visual, sin código.",
        icon: "construct",
        category: "platform",
        difficulty: "beginner",
        popularity: 3,
        documentation: "https://www.construct.net/en/make-games/manuals",
        installation: [
          "Abrir construct.net en navegador",
          "Crear cuenta gratuita",
          "Comenzar con template o proyecto vacío",
          "Todo funciona en el navegador",
        ],
        features: [
          "No requiere programación",
          "Event-based visual scripting",
          "Runs completamente en navegador",
          "Export a todas las plataformas",
          "Colaboración en tiempo real",
        ],
        useCases: [
          "Primeros juegos sin programar",
          "Prototipado super rápido",
          "Juegos educativos para niños",
          "Desarrollo colaborativo",
          "Game jams y experimentos rápidos",
        ],
      },
    ],
    roadmap: [
      {
        title: "Fundamentos de Game Design",
        description: "Conceptos esenciales del desarrollo de juegos",
        items: [
          "Mecánicas, dinámicas y estética de juegos",
          "Game loops y sistemas de juego",
          "Level design y progression",
          "Player psychology y engagement",
          "Documentación de game design (GDD)",
        ],
      },
      {
        title: "Herramientas y Motor de Juegos",
        description: "Domina tu engine principal",
        items: [
          "Unity para versatilidad multiplataforma",
          "Unreal para gráficos avanzados",
          "Godot para proyectos indie",
          "Scripting y programación del engine",
          "Asset management y optimization",
        ],
      },
      {
        title: "Arte y Audio",
        description: "Creación de assets visuales y sonoros",
        items: [
          "2D art (sprites, animations, UI)",
          "3D modeling y texturing básico",
          "Audio design y música para juegos",
          "VFX y particle systems",
          "Herramientas: Blender, Aseprite, Audacity",
        ],
      },
      {
        title: "Programación y Sistemas",
        description: "Desarrollo de funcionalidades avanzadas",
        items: [
          "Gameplay programming patterns",
          "AI para NPCs y enemigos",
          "Physics y collision detection",
          "Networking y multiplayer básico",
          "Save/load systems y persistence",
        ],
      },
      {
        title: "Testing y Distribución",
        description: "Pulimiento y lanzamiento",
        items: [
          "Playtesting y user feedback",
          "Performance optimization",
          "Platform-specific requirements",
          "Steam, App Stores, itch.io publishing",
          "Marketing y community building",
        ],
      },
    ],
    resources: [
      {
        title: "Unity Learn",
        type: "course",
        url: "https://learn.unity.com/",
        description: "Plataforma oficial de aprendizaje de Unity",
        free: true,
      },
      {
        title: "Unreal Engine Documentation",
        type: "documentation",
        url: "https://docs.unrealengine.com/",
        description: "Documentación completa de Unreal Engine",
        free: true,
      },
      {
        title: "Godot Documentation",
        type: "documentation",
        url: "https://docs.godotengine.org/",
        description: "Guías completas del motor Godot",
        free: true,
      },
      {
        title: "Game Programming Patterns",
        type: "documentation",
        url: "https://gameprogrammingpatterns.com/",
        description: "Libro gratuito sobre patrones de programación en juegos",
        free: true,
      },
      {
        title: "itch.io",
        type: "platform",
        url: "https://itch.io/",
        description: "Plataforma para publicar y distribuir juegos indie",
        free: true,
      },
      {
        title: "OpenGameArt",
        type: "tool",
        url: "https://opengameart.org/",
        description: "Assets gratuitos para juegos (sprites, música, SFX)",
        free: true,
      },
      {
        title: "Complete C# Unity Game Developer 2D",
        type: "course",
        url: "https://www.udemy.com/course/unitycourse/",
        description: "Curso completo de Unity en Udemy",
        free: false,
      },
      {
        title: "Blender",
        type: "tool",
        url: "https://www.blender.org/",
        description: "Software gratuito para modelado 3D y animación",
        free: true,
      },
      {
        title: "Aseprite",
        type: "tool",
        url: "https://www.aseprite.org/",
        description: "Editor especializado en pixel art y sprites",
        free: false,
      },
      {
        title: "Game Maker's Toolkit",
        type: "tutorial",
        url: "https://www.youtube.com/c/MarkBrownGMT",
        description: "Canal de YouTube con análisis de game design",
        free: true,
      },
    ],
  },
];
